name: 'ecommerce_master'
version: '1.0.0'
config-version: 2

profile: 'vfx_take_home_dbt_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  ecommerce_master:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  ecommerce_master:
    +schema: seeds