name: 'vfx_take_home_assignment'
version: '1.0.0'
config-version: 2

profile: 'vfx_take_home_dbt_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  vfx_take_home_assignment:
    staging:
      +materialized: view
      +schema: staging
    master:
      +materialized: table
      +schema: master

seeds:
  vfx_take_home_assignment:
    exchange_rates:
      +column_types:
        rate: float
        effective_date: date


